### ISSUE TITLE
kubestack systemd units update

### ISSUE THREAD

**Issue by rimusz** [kelseyhightower/kubestack#10]
Can we also update systemd units without rebuilding image?
As destroying servers just for that is not a good idea I think :)

**Comment by rimusz** [comment]
hmm maybe terraform remote-exec provisioner can help over here

**Comment by bakins** [comment]
I think the provisioners only run when a vm is created.  Any updates to a running cluster would probably need to happen outside of terraform.

**Comment by rimusz** [comment]
I will dig to terrafrom a bit more, as it looks it can be possible with it

**Comment by rimusz** [comment]
I think the best is to create a new image and provision it again, as terraform is only for infrastructure deployment and changes
