### ISSUE TITLE
support for different sizes of etcd clusters

### ISSUE THREAD

**Issue by rimusz** [kelseyhightower/kubestack#11]
Would be handy to have support for:
1) standalone etcd cluster machines (useful to use for development clusters)
2) 3x etcd cluster
3) 5x etcd cluster

**Comment by kelseyhightower** [comment]
@rimusz The good thing everything was automated via terraform in a way that supports this. We just need to turn the etcd count to a variable and it should just work.

**Comment by rimusz** [comment]
@kelseyhightower  ok, will try to update the terraform config then
