### ISSUE TITLE
change where kubestack-account.json file gets stored

### ISSUE THREAD

**Issue by rimusz** [kelseyhightower/kubestack#6]
@kelseyhightower  I would advise to change `/etc/kubestack-account.json` to `~/kubestack/kubestack-account.json` to store the file.

It is much easier to find and clean things up, no needs to put under main system `/etc` folder.

If you are happy with my suggestion, I can make all necessary changes and issue the PR for that.

**Comment by jumanjiman** [comment]
imho it's better to store things in system folder.
home dir encourages direct user login.

**Comment by rimusz** [comment]
@jumanjiman system folder need root access :)
that file is only to bootstrap things but not for the constant use

**Comment by kelseyhightower** [comment]
@rimusz @jumanjiman Currently that completely configurable!

**Comment by jumanjiman** [comment]
in my use case, I currently bootstrap to a puppet agent, then it deploys
everything else needed to get started. the agent runs in a container, so I
minimize the mounts as much as possible. I'm flexible, but anything that
allows control is by definition privileged.

**Comment by rimusz** [comment]
everybody has different use cases, so let's leave it up to user then.
